import type { Metadata } from "next";
import "@/styles/globals.css";
import { ThemeModeScript } from 'flowbite-react';
import localFont from "next/font/local";
const iranSans = localFont({
  src: "../../public/fonts/IRANSans(FaNum).ttf",
  variable: "--font-iran-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="fa" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body
        className={`${iranSans.variable}  antialiased flex flex-col `}
      >
        {children}
      </body>
    </html>
  );
}
