import type { Metadata } from "next";
import "@/styles/globals.css";
import NavbarIndex from "@/components/navbar";
import SiteFooter from "@/components/landing/SiteFooter";
export const metadata: Metadata = {
      title: "صفحه اصلی",
      description: "Generated by create next app",
};

export default function PublicHome({
      children,
}: Readonly<{
      children: React.ReactNode;
}>) {
      return (
            <>
                  <NavbarIndex />
                  <main>
                        {children}
                  </main>
                  {/* <Footer /> */}
            </>
      );
}
